### ISSUE TITLE
AdvancedControl : Error when building

### ISSUE THREAD

**Issue by ghost** [sayan7848/device_xiaomi_mido#1]
This commit : https://github.com/sayan7848/device_xiaomi_mido/commit/aefb10eac8543f54c192fafcf43bbd21625b3f8e

Make error when building in some ROMs. Due to unmatch theme preferences

**Comment by henriquee0023** [comment]
since not every rom uses the same preferences, this should be changed every time you'll build a different rom.

**Comment by sayan7848** [comment]
In addition to above explanation, I realize that it is not the most convenient way. Due to my initial design decisions, I wanted to use as much standard apis as possible. However, we have now much deviated from standard sdk apis. I shall change the theming to xml base in near future.
